/*
ACTION TYPES
*/

//Customers Actions
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const WAITING_RESPONSE = "WAITING_RESPONSE";
export const FETCHING_ERROR = "FETCHING_ERROR";
export const ORDER_CUSTOMERS_LIST = "ORDER_CUSTOMERS_LIST";
export const FILTER_CUSTOMERS_LIST = "FILTER_CUSTOMERS_LIST";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SERVER_POST_RESPONSE = "SERVER_POST_RESPONSE";
